# Generated by Django 5.2.5 on 2025-08-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du produit')),
                ('marque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marque')),
                ('categorie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PrixProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_produits', to='magasin.magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='produit.produit')),
            ],
            options={
                'verbose_name': 'Prix du produit',
                'verbose_name_plural': 'Prix des produits',
                'unique_together': {('produit', 'magasin')},
            },
        ),
    ]
