# Generated by Django 5.2.5 on 2025-08-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ville', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la commune')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='ville.ville')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['nom'],
                'unique_together': {('nom', 'ville')},
            },
        ),
    ]
